# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57a61dca991b847015f2ad1af14e975d58eff9488833f77d164a3059cba6b88d3247865a16c940ae99c446dc5355b04c836830b68ea012a4c316bdb4826ee010

test:
  secret_key_base: 8fc3fbc875306ae9befdd953ff81bd9ee773aeeed31f0c0c811b0f0b11e2dcf4157d9a02fb6bd92a6c28aa54624883c67987952421b607b00d1ec5827e7521fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
